version: '3'

services:
  database:
    image: mysql:latest
    container_name: database-service
    environment:
      MYSQL_ROOT_PASSWORD: khalid
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
  backend:
    build: ./backend/.
    image: backend-image
    container_name: backend-service
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database
volumes:
  mysql_data:

