version: '3'

services:
  database:
    image: mysql:latest
    container_name: database-service
    environment:
      MYSQL_ROOT_PASSWORD: khalid
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:

